"maps"
{
    "dota_old_730"
    {
        "type"          "old_map"
        "values"
        {
            "shops"     "scripts/kv/maps/730/shops.kv"
            // "items"     "scripts/npc/items/730/items.kv"
        }
    }

    "dota"
    {
        // "type"          "default"

        "type"          "reference"
        "name"          "dota_old_730"
        "overrides"
        {

        }
    }
}