"Wearables"
{
    "npc_dota_hero_nevermore"
    {
        "Default"
        {
            "Abilities"
            {
                "nevermore_shadowraze1_custom_730"      "nevermore/nevermore_shadowraze1"
                "nevermore_shadowraze2_custom_730"      "nevermore/nevermore_shadowraze2"
                "nevermore_shadowraze3_custom_730"      "nevermore/nevermore_shadowraze3"
                "nevermore_necromastery_custom_730"     "nevermore/nevermore_necromastery"
                "nevermore_dark_lord_custom_730"        "nevermore/nevermore_dark_lord"
                "nevermore_requiem_custom_730"          "nevermore/nevermore_requiem"
            }
        }

        "Arcana"
        {
            "ModelPath"     "models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl"

            "MetaInfo"
            {
                "IsArcana"  "1"
            }

            "Abilities"
            {
                "nevermore_shadowraze1_custom_730"      "nevermore/nevermore_shadowraze1_arcana"
                "nevermore_shadowraze2_custom_730"      "nevermore/nevermore_shadowraze2_arcana"
                "nevermore_shadowraze3_custom_730"      "nevermore/nevermore_shadowraze3_arcana"
                "nevermore_necromastery_custom_730"     "nevermore/nevermore_necromastery_arcana"
                "nevermore_dark_lord_custom_730"        "nevermore/nevermore_dark_lord_arcana"
                "nevermore_requiem_custom_730"          "nevermore/nevermore_requiem_arcana"
            }

            "Particles"
            {
                "particles/units/heroes/hero_nevermore/nevermore_shadowraze.vpcf"           "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_shadowraze.vpcf"

                "particles/units/heroes/hero_nevermore/nevermore_wings.vpcf"                "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_wings.vpcf"
                "particles/units/heroes/hero_nevermore/nevermore_requiemofsouls.vpcf"       "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_requiemofsouls.vpcf"
                "particles/units/heroes/hero_nevermore/nevermore_requiemofsouls_line.vpcf"  "particles/econ/items/shadow_fiend/sf_fire_arcana/sf_fire_arcana_requiemofsouls_line.vpcf"
            }

            "Sounds"
            {
                "Hero_Nevermore.Shadowraze"             "Hero_Nevermore.Shadowraze.Arcana"

                "Hero_Nevermore.RequiemOfSouls"         "Hero_Nevermore.ROS.Arcana"
                "Hero_Nevermore.RequiemOfSoulsCast"     "Hero_Nevermore.ROS.Arcana.Cast"
            }
        }
    }
}