"Wearables"
{
    "npc_dota_hero_nevermore"
    {
        "Default"
        {
            "Abilities"
            {
                "nevermore_shadowraze1_custom_730"      "nevermore/nevermore_shadowraze1"
                "nevermore_shadowraze2_custom_730"      "nevermore/nevermore_shadowraze2"
                "nevermore_shadowraze3_custom_730"      "nevermore/nevermore_shadowraze3"
                "nevermore_necromastery_custom_730"     "nevermore/nevermore_necromastery"
                "nevermore_dark_lord_custom_730"        "nevermore/nevermore_dark_lord"
                "nevermore_requiem_custom_730"          "nevermore/nevermore_requiem"
            }
        }

        "Arcana"
        {
            "ModelPath"     "models/heroes/shadow_fiend/shadow_fiend_arcana.vmdl"
            "Abilities"
            {
                "nevermore_shadowraze1_custom_730"      "nevermore/nevermore_shadowraze1_arcana"
                "nevermore_shadowraze2_custom_730"      "nevermore/nevermore_shadowraze2_arcana"
                "nevermore_shadowraze3_custom_730"      "nevermore/nevermore_shadowraze3_arcana"
                "nevermore_necromastery_custom_730"     "nevermore/nevermore_necromastery_arcana"
                "nevermore_dark_lord_custom_730"        "nevermore/nevermore_dark_lord_arcana"
                "nevermore_requiem_custom_730"          "nevermore/nevermore_requiem_arcana"
            }
        }
    }
}