"Wearables"
{
    "npc_dota_hero_tinker"
    {
        "Default"
        {
            "Abilities"
            {
                "tinker_laser_custom_730"                   "tinker/tinker_laser"
                "tinker_heat_seeking_missile_custom_730"    "tinker/tinker_heat_seeking_missile"
                "tinker_defense_matrix_custom_730"          "tinker/tinker_defense_matrix"
                "tinker_march_of_the_machines_custom_730"   "tinker/tinker_march_of_the_machines"
                "tinker_keen_teleport_custom_730"           "tinker/tinker_keen_teleport"
                "tinker_rearm_custom_730"                   "tinker/tinker_rearm"
            }
        }

        "Immortal_Laser"
        {
            "ModelPath"     "models/items/tinker/tinker_ti10_immortal_laser/tinker_ti10_immortal_laser.vmdl"
            "Abilities"
            {
                "tinker_laser_custom_730"                   "tinker/tinker_laser_immortal"
            }
        }

        "Immortal_March"
        {
            "ModelPath"     "models/items/tinker/roller_mawster/roller_mawster.vmdl"
            "Abilities"
            {
                "tinker_march_of_the_machines_custom_730"   "tinker/tinker_march_of_the_machines_immortal"
            }
        }
    }
}