"Wearables"
{
    "npc_dota_hero_techies"
    {
        "Default"
        {
            "Abilities"
            {
                "techies_land_mines_custom_730"         "techies/techies_land_mines"
                "techies_minefield_sign_custom_730"     "techies/techies_minefield_sign"
                "techies_remote_mines_custom_730"       "techies/techies_remote_mines"
            }
        }

        "Arcana"
        {
            "SkinPriority"  "1"
            "ModelPath"     "models/items/techies/bigshot/bigshot.vmdl"
            "Abilities"
            {
                "techies_minefield_sign_custom_730"     "techies/techies_minefield_sign_arcana"
                "techies_remote_mines_custom_730"       "techies/techies_remote_mines_arcana"
            }
        }

        "Immortal"
        {
            "SkinPriority"  "0"
            "ModelPath"     "models/items/techies/techies_ti9_immortal_cart/techies_ti9_immortal_cart.vmdl"
            "Abilities"
            {
                "techies_land_mines_custom_730"         "techies/techies_land_mines_immortal"
                "techies_remote_mines_custom_730"       "techies/techies_remote_mines_immortal"
            }
        }
    }
}