"Wearables"
{
    "npc_dota_hero_tinker"
    {
        "Default"
        {
            "Abilities"
            {
                "tinker_laser_custom_730"                   "tinker/tinker_laser"
                "tinker_heat_seeking_missile_custom_730"    "tinker/tinker_heat_seeking_missile"
                "tinker_defense_matrix_custom_730"          "tinker/tinker_defense_matrix"
                "tinker_march_of_the_machines_custom_730"   "tinker/tinker_march_of_the_machines"
                "tinker_keen_teleport_custom_730"           "tinker/tinker_keen_teleport"
                "tinker_rearm_custom_730"                   "tinker/tinker_rearm"
            }
        }

        "Immortal_Laser"
        {
            "ModelPath"     "models/items/tinker/tinker_ti10_immortal_laser/tinker_ti10_immortal_laser.vmdl"
            "Abilities"
            {
                "tinker_laser_custom_730"                   "tinker/tinker_laser_immortal"
            }

            "Particles"
            {
                "particles/units/heroes/hero_tinker/tinker_laser.vpcf"  "particles/econ/items/tinker/tinker_ti10_immortal_laser/tinker_ti10_immortal_laser.vpcf"
            }
        }

        "Immortal_March"
        {
            "ModelPath"     "models/items/tinker/roller_mawster/roller_mawster.vmdl"
            "Abilities"
            {
                "tinker_march_of_the_machines_custom_730"   "tinker/tinker_march_of_the_machines_immortal"
            }

            "Particles"
            {
                "particles/units/heroes/hero_tinker/730/tinker_machine.vpcf"    "particles/econ/items/tinker/tinker_motm_rollermaw/tinker_rollermaw.vpcf"
                "particles/units/heroes/hero_tinker/730/tinker_motm.vpcf"       "particles/econ/items/tinker/tinker_motm_rollermaw/tinker_rollermaw_motm.vpcf"
            }

            "Sounds"
            {
                "Hero_Tinker.March_of_the_Machines.Cast"    "Hero_Tinker.March_of_the_Machines.Cast.Rollermawster"
            }
        }

        "Immortal_Boots"
        {
            "ModelPath"     "models/items/tinker/boots_of_travel.vmdl"

            "Particles"
            {
                "particles/items2_fx/teleport_start.vpcf"   "particles/econ/items/tinker/boots_of_travel/teleport_start_bots.vpcf"
                "particles/items2_fx/teleport_end.vpcf"     "particles/econ/items/tinker/boots_of_travel/teleport_end_bots.vpcf"
            }
            
            "Sounds"
            {
                "Portal.Loop_Appear"      "Hero_Tinker.MechaBoots.Loop"
            }
        }
    }
}