"DOTAHeroes"
{
    "npc_dota_hero_techies_old_730"
    {
        "override_hero"                 "npc_dota_hero_techies"                         // Hero to override

        "Ability1"                      "techies_land_mines_custom_730"                 // Ability 1
        "Ability2"                      "techies_stasis_trap_custom_730"                // Ability 2
        "Ability3"                      "techies_suicide_custom_730"                    // Ability 3
        "Ability4"                      "techies_focused_detonate_custom_730"           // Ability 4
        "Ability5"                      "techies_minefield_sign_custom_730"             // Ability 5
        "Ability6"                      "techies_remote_mines_custom_730"               // Ability 6
        "Ability7"                      "generic_hidden"                                // Ability 7 (Reactive Tazer Stop)

        "Ability10"                     "special_bonus_magic_resistance_20"             // Talent 10 right
        "Ability11"                     "special_bonus_unique_techies_730_custom"       // Talent 10 left
        "Ability12"                     "special_bonus_unique_techies_730_custom_2"     // Talent 15 right
        "Ability13"                     "special_bonus_mp_regen_3"                      // Talent 15 left
        "Ability14"                     "special_bonus_movement_speed_40"               // Talent 20 right
        "Ability15"                     "special_bonus_unique_techies_730_custom_3"     // Talent 20 left
        "Ability16"                     "special_bonus_attack_damage_252"               // Talent 25 right
        "Ability17"                     "special_bonus_unique_techies_730_custom_4"     // Talent 25 left

        "ArmorPhysical"                 "5"
        "AttackDamageMin"               "9"
        "AttackDamageMax"               "11"

        "AttackRange"                   "700"
        "AttackAcquisitionRange"        "800"

        "AttributePrimary"              "DOTA_ATTRIBUTE_INTELLECT"
        "AttributeBaseStrength"         "19"
        "AttributeStrengthGain"         "2.5"
        "AttributeBaseIntelligence"     "25"
        "AttributeIntelligenceGain"     "3.3"
        "AttributeBaseAgility"          "14"
        "AttributeAgilityGain"          "1.3"

        "StatusHealthRegen"             "0.25"
        "StatusManaRegen"               "1.0"

        "MovementSpeed"                 "320"
        "MovementTurnRate"              "0.6"

        "Facets"                        ""
    }
}